### ISSUE TITLE
Fabric REST API

### ISSUE THREAD

**Issue by andrewpmartinez** [openziti/fabric#67]
Develop a workflow for a Fabric REST API and REST API platform that the Edge can utilize.

- Open API documentation (aka swagger)
- Generated server flow
- Initial support for the Fabric JSON Gateway API endpoints

**Comment by plorenz** [comment]
Notes from #55 

Create a version of the management API accessible via REST. Framework should be extensible so the edge can use/extend the same framework to expose its management API.

Will need to be pluggable in some way so that different authentication mechanisms can be used. For example, when running in pure fabric mode, the controller may use certificate based authentication. When running with the edge components, it should allow using the edge authentication mechanisms.

We do not need to support both at the same time. If running with the edge, the pure fabric certificate mode does not need to be supported.

**Comment by plorenz** [comment]
Completed
